"""Initial migration

Revision ID: 247b0fa98991
Revises: a2f20f3859ca
Create Date: 2024-06-29 23:02:13.994581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247b0fa98991'
down_revision = 'a2f20f3859ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(), nullable=False),
    sa.Column('employment', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=False),
    sa.Column('responsibility', sa.String(), nullable=False),
    sa.Column('alternate_url', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('timeDay', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
