"""Initial migration

Revision ID: 3b7ad4c10cdb
Revises: 4e216e8cd027
Create Date: 2024-06-30 22:50:43.876765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7ad4c10cdb'
down_revision = '4e216e8cd027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=200), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('salaryFrom', sa.Integer(), nullable=True),
    sa.Column('salaryTo', sa.Integer(), nullable=True),
    sa.Column('requirement', sa.String(length=350), nullable=False),
    sa.Column('responsibility', sa.String(length=350), nullable=False),
    sa.Column('alternate_url', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=70), nullable=True),
    sa.Column('timeDay', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vacancy')
    # ### end Alembic commands ###
