"""Initial migration

Revision ID: 9b3bb76ba37b
Revises: feebf023c8dd
Create Date: 2024-06-29 23:18:04.629766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3bb76ba37b'
down_revision = 'feebf023c8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=700), nullable=False),
    sa.Column('employer', sa.String(length=700), nullable=False),
    sa.Column('address', sa.String(length=700), nullable=False),
    sa.Column('salary', sa.String(length=700), nullable=False),
    sa.Column('requirement', sa.String(length=700), nullable=False),
    sa.Column('responsibility', sa.String(length=700), nullable=False),
    sa.Column('alternate_url', sa.String(length=700), nullable=True),
    sa.Column('time', sa.String(length=700), nullable=True),
    sa.Column('timeDay', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
