"""Initial migration

Revision ID: 742ead5f9fd7
Revises: 4b29ca838f69
Create Date: 2024-06-29 22:58:05.152100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742ead5f9fd7'
down_revision = '4b29ca838f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=200), nullable=False),
    sa.Column('employment', sa.String(length=700), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('salary', sa.String(length=30), nullable=False),
    sa.Column('requirement', sa.String(length=700), nullable=False),
    sa.Column('responsibility', sa.String(length=700), nullable=False),
    sa.Column('alternate_url', sa.String(length=700), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('timeDay', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
