"""Initial migration

Revision ID: 86170d0974bb
Revises: eb4927c67f11
Create Date: 2024-06-30 21:50:41.329008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86170d0974bb'
down_revision = 'eb4927c67f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=200), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('salaryFrom', sa.Integer(), nullable=False),
    sa.Column('salaryTo', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.String(length=350), nullable=False),
    sa.Column('responsibility', sa.String(length=350), nullable=False),
    sa.Column('alternate_url', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=70), nullable=True),
    sa.Column('timeDay', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
