"""Initial migration

Revision ID: eb4927c67f11
Revises: 9b3bb76ba37b
Create Date: 2024-06-30 00:45:25.779927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4927c67f11'
down_revision = '9b3bb76ba37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=700), nullable=False),
    sa.Column('employer', sa.String(length=700), nullable=False),
    sa.Column('address', sa.String(length=700), nullable=False),
    sa.Column('salary', sa.String(length=700), nullable=False),
    sa.Column('requirement', sa.String(length=700), nullable=False),
    sa.Column('responsibility', sa.String(length=700), nullable=False),
    sa.Column('alternate_url', sa.String(length=700), nullable=True),
    sa.Column('time', sa.String(length=700), nullable=True),
    sa.Column('timeDay', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
